// What is javascript

/*
-> JavaScript is a dynamic computer programming language.
-> It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
-> JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.Complementary to and integrated with HTML.Open and cross-platform
*/

/****   JavaScript Values   ****/
//  -> The JavaScript syntax defines two types of values

/*
    -> Fixed values are called Literals.
    -> Variable values are called Variables.
 */

/* How To Create Javascript File And How To Add In Html Document */

/*
    1.] Head
    2.] Body
    3.] Link

*/

/**** Using console in javascript ****/

{
    // var a = 20;
    // var b = 30;
    // var c = a * b;
    // document.write(c)
    // console.log(c);
}


/**** var variable type / box variable name / = assignement / 60 assiged values ****/

// javascript is case-sensitive language

/******** Variable Useing var() In Javascript ************/

{
    // var names = "brinza";
    // console.log(names);

    // var Names = "foo";
    // var names = "Javascript";
    // console.log(Names);

    // var thisis = 15;
    // var thatis = 45;
    // console.log(thatis*thatis);

    // var box1 = "toys";
    // var box1 = "cloths";
    // console.log(box1);
    // box1 = "apple"
    // console.log(box1);

}


/******* New Html Element Add In Though Javascript *********/

{
    // var newelement = document.createElement("h1");
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);

    // var newelement=document.createElement("marquee" , Option);
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);

    // var newelement=document.createElement("p");
    // newelement.textContent="how are you!";
    // document.body.appendChild(newelement);
}

/* Document.Write In Javascript */

// document.write('hello javascript!');


/********** Js Comments *************/

// single-line comments

/* multi-line 
comments */


/*var Fun = "this is fun days!"
var Fun = "this is fun days!"
var Fun = "this is fun days!"
var Fun = "this is fun days!"
var Fun = "this is fun days!"
var Fun = "this is fun days!"
var Fun = "this is fun days!"*/


// Template literals

{
    // var _nameone = "this is javascript";

    // var box = "20";

    // var _nametwo = `This is javascript langauge and its
    //  dynamic language for create Html Pages ${box} `;

    // var Fun = "this is fun days!"
    
    // console.log(_nameone);
    // console.log(_nametwo + Fun);
    // console.log(_nameone + _nametwo);

    // var all = _nameone + box  + _nametwo  + Fun;
    // console.log(all);

    // console.log(alert(`${_nameone}  ${_nametwo}`));

    // console.log(alert( _nameone  +  _nametwo));
}

// Rules For Naming JavaScript Variables

{
    // // valid
    // let a = 'hello';
    // let _a = 'hello';
    // let $a = 'hello';

    // console.log($_a);
}
{
    //invalid
    // let a1 = 'hello'; // this gives an error
    // console.log();
}

// JavaScript is case-sensitive. So y and Y are different variables

{
    // let y = "hi";
    // let Y = 5;

    // console.log(y);
    // console.log(Y); 
}

// Keywords Cannot Be Used As Variable Names.

{
    //invalid
    // let new = 5; // Error! new is a keyword.
}

/*  

Name must start with a letter (a to z or A to Z), underscore( _ ), or dollar( $ ) sign. After first letter we can use digits (0 to 9), for example value1.

*/





